server: 
  port: 8080 # Sudah disesuaikan untuk Koyeb
  address: 0.0.0.0

lavalink:
  plugins:
    # Kode ini ditambahkan agar YouTube bisa digunakan di Lavalink versi terbaru
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.4"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: "bojonegoro" # Jangan lupa ubah ini!
    sources:
      youtube: false # Dibiarkan false karena kita sudah pakai plugin di atas
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true 
      local: false
    filters: 
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400 
    frameBufferDurationMs: 5000 
    opusEncodingQuality: 10 
    resamplingQuality: LOW 
    trackStuckThresholdMs: 10000 
    useSeekGhosting: true 
    youtubePlaylistLoadLimit: 6 
    playerUpdateInterval: 5 
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    soundcloudFilterOutPreviewTracks: false

# Pengaturan log bawaan (dibiarkan standar)
logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
